POST http://localhost:5049/OlympicWinners/winners
Content-Type: application/json

{
    "StartRow" : 5,
    "EndRow" : 10,
    "RowGroupCols" :[
    ],
    "ValueCols" : [],
    "PivotCols" : [],
    "GroupKeys" : [],
    "SortModel" : [],
    "filterModel": {}
}