POST http://localhost:5049/api/winners
Content-Type: application/json

{
 "startRow": 1,
 "endRow": 6,
 "rowGroupCols": [],
 "valueCols": [
  {
   "id": "gold",
   "aggFunc": "sum",
   "displayName": "Gold",
   "field": "gold"
  },
  {
   "id": "silver",
   "aggFunc": "sum",
   "displayName": "Silver",
   "field": "silver"
  },
  {
   "id": "bronze",
   "aggFunc": "sum",
   "displayName": "Bronze",
   "field": "bronze"
  }
 ],
 "pivotCols": [],
 "pivotMode": false,
 "groupKeys": [],
 "filterModel": {
  "athlete": {
   "filterType": "text",
   "type": "contains",
   "filter": "phelp"
  }
 },
 "sortModel": []
}