POST http://localhost:5049/OlympicWinners/winners
Content-Type: application/json

{
 "startRow": 5,
 "endRow": 10,
 "rowGroupCols": [
  {
   "id": "country",
   "displayName": "Country",
   "field": "country"
  },
  {
   "id": "sport",
   "displayName": "Sport",
   "field": "sport"
  }
 ],
 "valueCols": [
  {
   "id": "gold",
   "aggFunc": "sum",
   "displayName": "Gold",
   "field": "gold"
  },
  {
   "id": "silver",
   "aggFunc": "sum",
   "displayName": "Silver",
   "field": "silver"
  },
  {
   "id": "bronze",
   "aggFunc": "sum",
   "displayName": "Bronze",
   "field": "bronze"
  }
 ],
 "pivotCols": [],
 "pivotMode": false,
 "groupKeys": [
  "Argentina"
 ],
 "filterModel": {},
 "sortModel": [
  {
   "colId": "country",
   "sort": "asc"
  },
  {
   "colId": "sport",
   "sort": "asc"
  }
 ]
}